property.log.dir=logs/${spring:spring.application.name}
property.log.dir.info=${log.dir}/info
property.log.dir.error=${log.dir}/error
property.log.pattern=%d{yyyy-MM-dd HH:mm:ss} - %p - %m%n
# Console
appender.0.type=Console
appender.0.name=Console
appender.0.target=SYSTEM_OUT
appender.0.layout.type=PatternLayout
appender.0.layout.pattern=${log.pattern}
# Info
appender.1.type=RollingFile
appender.1.name=InfoFile
appender.1.fileName=${log.dir.info}/info.log
appender.1.filePattern=${log.dir.info}/$${date:yyyy-MM}/info-%d{yyyy-MM-dd}.log.gz
appender.1.layout.type=PatternLayout
appender.1.layout.pattern=${log.pattern}
appender.1.filter.0.type=LevelRangeFilter
appender.1.filter.0.minLevel=WARN
appender.1.filter.0.onMatch=ACCEPT
appender.1.filter.0.onMismatch=DENY
appender.1.policies.type=SizeBasedTriggeringPolicy
appender.1.policies.size=10MB
appender.1.strategy.type=DefaultRolloverStrategy
appender.1.strategy.max=30
# Error
appender.2.type=RollingFile
appender.2.name=ErrorFile
appender.2.fileName=${log.dir.error}/error.log
appender.2.filePattern=${log.dir.error}/$${date:yyyy-MM}/error-%d{yyyy-MM-dd}.log.gz
appender.2.layout.type=PatternLayout
appender.2.layout.pattern=${log.pattern}
appender.2.filter.0.type=ThresholdFilter
appender.2.filter.0.level=ERROR
appender.2.filter.0.onMatch=ACCEPT
appender.2.filter.0.onMismatch=DENY
appender.2.policies.type=SizeBasedTriggeringPolicy
appender.2.policies.size=10MB
appender.2.strategy.type=DefaultRolloverStrategy
appender.2.strategy.max=30
# Root
rootLogger.level=INFO
rootLogger.appenderRef.0.ref=Console
rootLogger.appenderRef.1.ref=InfoFile
rootLogger.appenderRef.2.ref=ErrorFile
