# Database configuration for Spring Boot application
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tywzrxamjanqqewfxgns
spring.datasource.password=Nhung300898@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

app.security.jwt.secret=${JWT_SECRET:change-this-secret}
app.security.jwt.excluded-paths=/auth/**,/login,/register,/error