# Database configuration for Spring Boot application
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tywzrxamjanqqewfxgns
spring.datasource.password=Nhung300898@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
backend.cors.allowed-origins=http://localhost:4200

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : [ip - %X{ip:-}] [path - %X{uri:-}] [req - %X{traceId:-}] [user - %X{userName:-}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : [ip - %X{ip:-}] [path - %X{uri:-}] [req - %X{traceId:-}] [user - %X{userName:-}] - %msg%n

app.security.jwt.secret=web-backend
app.security.jwt.expiration-seconds=3600
app.security.jwt.excluded-paths=/auth/**,/login,/register,/error

app.middleware.encryption.enabled=true
app.middleware.encryption.excluded-paths=/auth/public-key,/auth/signup,/auth/register,/login,/register,/error
