spring.application.name=backend-core
spring.config.import=optional:file:./config/shared.properties

app.security.jwt.secret=${JWT_SECRET:change-this-secret}
app.security.jwt.excluded-paths=/auth/**,/login,/register,/error
