spring.application.name=backend-core
spring.config.import=optional:file:config/shared.properties,optional:file:../config/shared.properties
spring.logging.config=optional:file:config/log4j2.properties,optional:file:../config/log4j2.properties
